import "./globals.css";
import { Open_Sans } from "next/font/google";
import { Providers } from "./providers";
const opensans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "2023.전남동부권사회과연구회",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={opensans.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
